### ISSUE TITLE
Publish to maven repo

### ISSUE THREAD

**Issue by Saravanan21** [kevinsamyn/sportmonks-soccer#2]
Is this published on any maven repo? How do I pull the library in to use? Some extra install instructions in the readme would be very helpful.

**Comment by kevinsamyn** [comment]
It's nos available on maven central

**Comment by sima-hindiyeh** [comment]
it is now or not published? because im unable to pull it from central

**Comment by kevinsamyn** [comment]
Yes

<dependency>
  <groupId>com.github.kevinsamyn.sportmonks-soccer-api</groupId>
  <artifactId>sportmonks-soccer-api</artifactId>
  <version>2.1.3.1</version>
</dependency>

Le jeu. 17 sept. 2020 à 18:34, sima-hindiyeh <notifications@github.com> a
écrit :
