### ISSUE TITLE
Como usar a API? tem exemplos mais claros?

### ISSUE THREAD

**Issue by csdiftec** [kevinsamyn/sportmonks-soccer#4]
Olá, 
Estou usando sua api de monitoramento de resultados de jogos criei uma chamada para um endPoint porem estou recebendo a resposta desta forma;
` "com.api.data.entity.League@45362ea6, com.api.data.entity.League@2f98ds398]"`
chamada:
```
 final APIClient instance = APIClient.getInstance("API String");
 
   LeaguesEndPoint fx=instance.getLeaguesEndPointInstance();
    List<League> response = fx.findAll();
  System.out.println(response);
```
como pegar corretamente esses dados?

**Comment by kevinsamyn** [comment]
Println on list show object références because toString method is not overrided. You have to iterate on each.
