### ISSUE TITLE
Maven Should use https instead of http

### ISSUE THREAD

**Issue by sima-hindiyeh** [kevinsamyn/sportmonks-soccer#5]
trying to use the library is showing ReasonPhrase:HTTPS Required.  error

Effective January 15, 2020, The Central Repository no longer supports insecure communication over plain HTTP and requires that all requests to the repository are encrypted over HTTPS.

If you're receiving this error, then you need to replace all URL references to Maven Central with their canonical HTTPS counterparts.

can you update to use https instead of http.
thanks

**Comment by kevinsamyn** [comment]
Hi. I try to do that in the next days.

**Comment by kevinsamyn** [comment]
Can you give more details about your issue. I personnaly use this dependencies in an other project without issue.

Thanks

**Comment by sima-hindiyeh** [comment]
I think it is because it wasnt on central. But im trying to use now from
central, it says no such repo. am i missing something?

**Comment by kevinsamyn** [comment]
Nothing
